<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClawSharp.Core\ClawSharp.Core.csproj" />
    <ProjectReference Include="..\ClawSharp.Tools\ClawSharp.Tools.csproj" />
    <ProjectReference Include="..\ClawSharp.Tasks\ClawSharp.Tasks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.4.0" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
